---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ricsanfre.fluentbit
      fluentbit_service_enable_metrics: true
      # Default inputs
      fluentbit_inputs:
        - name: tail
          tag: auth
          path: /var/log/auth.log
          path_key: log_file
          DB: /run/fluent-bit-auth.state
          Parser: syslog-rfc3164
        - name: tail
          tag: syslog
          path: /var/log/syslog
          path_key: log_file
          DB: /run/fluent-bit-syslog.state
          Parser: syslog-rfc3164
      # Default outputs
      fluentbit_outputs:
        - name: stdout
          match: "*"
