---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ricsanfre.fluentbit
      fluentbit_service_enable_metrics: true
      # Default inputs
      fluentbit_inputs:
        - name: tail
          tag: auth
          path: /var/log/auth.log
          path_key: log_file
          DB: /run/fluent-bit-auth.state
          Parser: syslog-rfc3164
        - name: tail
          tag: syslog
          path: /var/log/syslog
          path_key: log_file
          DB: /run/fluent-bit-syslog.state
          Parser: syslog-rfc3164
      # Default outputs
      fluentbit_outputs:
        - name: stdout
          match: "*"
      # Parsers
      fluentbit_custom_parsers:
        - Name: syslog-rfc3164-nopri
          Format: regex
          Regex: /^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
          Time_Key: time
          Time_Format: "%b %d %H:%M:%S"
          Time_Keep: true
