---
# Install fluentbit

- name: Install | Install packages to allow HTTPS installation
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - ca-certificates
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release

- name: Install | Add fluent-bit apt-key
  apt_key:
    url: "{{ fluentbit_gpg_key }}"
    state: present

- name: Install | Add fluent-bit repository
  apt_repository:
    repo: '{{ fluentbit_apt_repo }}'
    state: present
    update_cache: true

- name: Install | Install fluentbit package
  package:
    name: "{{ fluentbit_pkg }}"
    state: present
    update_cache: true
  notify: Restart Fluentbit service
  tags: ['install']
