---
# handlers file for ansible-role-fluentbit

- name: Restart Fluentbit service
  ansible.builtin.service:
    name: "{{ fluentbit_service_name }}"
    enabled: true
    state: restarted
  become: true
  tags:
    - fluent-bit
