---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ricsanfre.fluentbit
      fluentbit_service_enable_metrics: true
      # Default inputs
      fluentbit_inputs: |
        [INPUT]
            Name dummy
            Tag dummy.log

      # Default outputs
      fluentbit_outputs: |
        [OUTPUT]
            Name stdout
            Match *
